# Generated by Django 3.0.2 on 2020-01-25 08:53

from django.db import migrations, models
import drfpasswordless.models


class Migration(migrations.Migration):

    dependencies = [
        ('drfpasswordless', '0004_auto_20200125_0853'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='callbacktoken',
            unique_together={('is_active', 'key', 'type', 'to_alias')},
        ),
    ]
