# Generated by Django 3.0.2 on 2020-11-17 04:10

from django.db import migrations, models
import drfpasswordless.models


class Migration(migrations.Migration):

    dependencies = [
        ('drfpasswordless', '0005_auto_20201117_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbacktoken',
            name='key',
            field=models.CharField(
                default=drfpasswordless.models.generate_numeric_token
            ),
        ),
    ]
