# Generated by Django 3.1.3 on 2020-11-17 18:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drfpasswordless', '0005_auto_20201025_1444'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='callbacktoken',
            unique_together={('is_active', 'key', 'type', 'to_alias', 'user_id')},
        ),
    ]
