# Generated by Django 3.1.14 on 2022-05-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfpasswordless', '0006_auto_20201117_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbacktoken',
            name='key',
            field=models.CharField(max_length=6),
        ),
    ]
