# Generated by Django 3.1.14 on 2022-07-27 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drfpasswordless', '0007_auto_20220503_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbacktoken',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
